[package]
name = "miden-stdlib"
version = "0.6.0"
description = "Miden VM standard library"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["cryptography", "mathematics"]
keywords = ["miden", "program", "stdlib"]
edition = "2021"
rust-version = "1.70"

[lib]
bench = false
doctest = false

[[test]]
name = "stdlib"
path = "tests/main.rs"

[features]
default = ["std"]
std = ["test-utils/std"]

[dependencies]
assembly = { package = "miden-assembly", default-features = false, path = "../assembly", version = "0.7" }

[dev-dependencies]
blake3 = "1.5"
miden-air = { package = "miden-air", path = "../air", version = "0.7", default-features = false }
num-bigint = "0.4"
processor = { package = "miden-processor", path = "../processor", version = "0.7", features = ["internals"], default-features = false }
serde_json = "1.0"
sha2 = "0.10"
sha3 = "0.10"
test-utils = { package = "miden-test-utils", path = "../test-utils" }
winter-air = { package = "winter-air", path = "../winterfell/air", version = "0.6" }
winter-fri = { package = "winter-fri", path = "../winterfell/fri", version = "0.6" }

[build-dependencies]
assembly = { package = "miden-assembly", path = "../assembly", version = "0.7" }
