[package]
name = "miden-assembly"
version = "0.7.0"
description = "Miden VM assembly language"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "language", "miden"]
edition = "2021"
rust-version = "1.70"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std"]

[dependencies]
num_enum = "0.7"
vm-core = { package = "miden-core", path = "../core", version = "0.7", default-features = false }
